services:
  ### Ollama ####
  ollama:
    restart: always # docker启动自动重启
    image: "ollama/ollama:latest"
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ${DATA_PATH_HOST}/ollama:/root/.ollama
    # environment:
      # - 'OLLAMA_HOST=0.0.0.0:11434'
    networks:
      - backend
    # GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu
    

  ### Open webui ####
  open-webui:
    restart: always # docker启动自动重启
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "${OPEN_WEBUI_PORT}:8080"
    volumes:
      - ${DATA_PATH_HOST}/open-webui-data:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
      - 'HF_ENDPOINT=https://hf-mirror.com'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - backend


networks:
  backend:
    driver: ${NETWORKS_DRIVER}